# Generated by Django 3.2.2 on 2021-05-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('coursetitle', models.CharField(max_length=500)),
                ('coursename', models.CharField(max_length=500)),
                ('coursesectioncode', models.IntegerField()),
                ('coursedepartment', models.CharField(max_length=500)),
                ('courseinstructor', models.CharField(max_length=500)),
            ],
        ),
    ]
