# Generated by Django 3.2.2 on 2021-05-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUS443FinalApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('major', models.CharField(max_length=500)),
                ('year', models.CharField(max_length=500)),
                ('gpa', models.CharField(max_length=500)),
            ],
        ),
    ]
